-- Schema definition - Database Structure

CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY;
    title VARCHAR(255) NOT NULL CHECK (LENGTH(title) > 0);
    description TEXT;
    completed BOOLEAN NOT NULL DEFAULT FALSE;
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
);